MODULE YOMABRT
USE PARKIND1, ONLY: JPIM
USE OML_MOD, ONLY : OML_LOCK_KIND
IMPLICIT NONE
SAVE
PUBLIC
INTEGER(KIND=JPIM) :: MAB_CNT = 0
INTEGER(KIND=OML_LOCK_KIND) :: MAB_LOCK(2) = (/-1,-1/)
END MODULE YOMABRT

