MODULE YOMERRTRAP
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
CONTAINS

SUBROUTINE SET_ERR_TRAP()
#ifdef RS6K
INTEGER(KIND=JPIM) SIGNAL_TRAP, SIGS(1),IRES

SIGS(1)  = 0
IRES     = SIGNAL_TRAP(0, SIGS)
#endif
END SUBROUTINE SET_ERR_TRAP

END MODULE YOMERRTRAP
