SUBROUTINE CREATE_STATID(CDSTATID,kstatid)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
implicit none
character(len=*), intent(in) :: CDSTATID
INTEGER(KIND=JPIM), intent(out) :: kstatid
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CREATE_STATID',0,ZHOOK_HANDLE)
kstatid = 0
read(CDSTATID,*,end=99,err=99) kstatid
99 continue
IF (LHOOK) CALL DR_HOOK('CREATE_STATID',1,ZHOOK_HANDLE)
END SUBROUTINE CREATE_STATID
