#define PY_SSIZE_T_CLEAN
#include <ctype.h>
#include <math.h>
#include <stdlib.h>
#include <Python.h>


static PyObject* odbTables_method(PyObject* Py_UNUSED(self), PyObject* Py_UNUSED(args)) 
{ 
Py_Initialize() ;
char *pytables[]  ={
"seqno@hdr",
"subseqno@hdr",
"bufrtype@hdr",
"subtype@hdr",
"subsetno@hdr",
"groupid@hdr",
"reportype@hdr",
"obstype@hdr",
"codetype@hdr",
"sensor@hdr",
"retrtype@hdr",
"instrument_type@hdr",
"stalt@hdr",
"date@hdr",
"time@hdr",
"distribtype@hdr",
"distribid@hdr",
"gp_dist@hdr",
"gp_number@hdr",
"numlev@hdr",
"numactiveb@hdr",
"checksum@hdr",
"sortbox@hdr",
"areatype@hdr",
"report_status@hdr",
"report_event1@hdr",
"report_rdbflag@hdr",
"report_blacklist@hdr",
"report_event2@hdr",
"thinningkey_1@hdr",
"thinningkey_2@hdr",
"thinningkey_3@hdr",
"thinningtimekey@hdr",
"sitedep@hdr",
"source@hdr",
"lat@hdr",
"lon@hdr",
"trlat@hdr",
"trlon@hdr",
"modsurf.offset@hdr",
"modsurf.len@hdr",
"statid@hdr",
"conv.offset@hdr",
"conv.len@hdr",
"sat.offset@hdr",
"sat.len@hdr",
"body@offset@hdr",
"body@len@hdr",
"errstat.offset@hdr",
"errstat.len@hdr",
"update_1.offset@hdr",
"update_1.len@hdr",
"update_2.offset@hdr",
"update_2.len@hdr",
"update_3.offset@hdr",
"update_3.len@hdr",
"auxiliary.offset@hdr",
"auxiliary.len@hdr",
"ensemble.offset@hdr",
"ensemble.len@hdr",
"gbrad.offset@hdr",
"gbrad.len@hdr",
"raingg.offset@hdr",
"raingg.len@hdr",
"surfbody@feedback.offset@hdr",
"surfbody@feedback.len@hdr",
"window_offset@hdr",
"entryno@body",
"obsvalue@body",
"varno@body",
"vertco_type@body",
"vertco_reference_1@body",
"vertco_reference_2@body",
"datum_anflag@body",
"datum_status@body",
"datum_event1@body",
"datum_rdbflag@body",
"datum_blacklist@body",
"datum_event2@body",
"varbc_ix@body",
"biascorr@body",
"biascorr_fg@body",
"tbcorr@body",
"bias_volatility@body",
"wdeff_bcorr@body",
"an_depar@body",
"fg_depar@body",
"actual_depar@body",
"qc_a@body",
"qc_l@body",
"qc_pge@body",
"fc_sens_obs@body",
"an_sens_obs@body",
"jacobian_peak@body",
"jacobian_peakl@body",
"jacobian_hpeak@body",
"jacobian_hpeakl@body",
"mf_vertco_type@body",
"mf_log_p@body",
"mf_stddev@body",
"nlayer@body",
} ; 
long unsigned int i = 0  ; 
while ( i <= sizeof (pytables)/ sizeof (double)-2   ) {
       i++  ; 
       printf ( "%s\n",  pytables[ i] ) ; 
}
return PyLong_FromLong(0) ; 
} 


static  PyObject*  odbVarno_method(PyObject* Py_UNUSED(self), PyObject* Py_UNUSED(args) )
{
Py_Initialize() ;
char *vars[]={"$u", 
"$v",
"$z",
"$dz",
"$rh",
"$pwc",
"$rh2m",
"$t",
"$td",
"$t2m",
"$td2m",
"$ts",
"$ptend",
"$w",
"$ww",
"$vv",
"$ch",
"$cm",
"$cl",
"$nh",
"$nn",
"$hshs",
"$c",
"$ns",
"$sdepth",
"$e",
"$tgtg",
"$spsp1",
"$spsp2",
"$rs",
"$eses",
"$is",
"$trtr",
"$rr",
"$jj",
"$vs",
"$ds",
"$hwhw",
"$pwpw",
"$dwdw",
"$gclg",
"$rhlc",
"$rhmc",
"$rhhc",
"$n",
"$sfall",
"$ps",
"$dd",
"$ff",
"$rawbt",
"$rawra",
"$satcl",
"$scatss",
"$du",
"$dv",
"$u10m",
"$v10m",
"$rhlay",
"$cllqw",
"$scatv",
"$scatu",
"$q",
"$scatwd",
"$scatws",
"$vsp",
"$vt",
"$o3lay",
"$height",
"$1dvar",
"$w2",
"$cpt",
"$tsts",
"$refl",
"$apdss",
"$bend_angle",
"$los",
"$aerod",
"$limb_radiance",
"$chem1",
"$chem2",
"$chem3",
"$chem4",
"$chem5",
"$cod",
"$rao",
"$od",
"$rfltnc",
"$nsoilm",
"$soilm",
"$flgt_phase",
"$height_assignment_method",
"$dopp",
"$ghg1",
"$ghg2",
"$ghg3",
"$bt_real",
"$bt_imaginary",
"$prc",
"$lnprc",
"$libksc",
"$ralt_swh",
"$ralt_sws",
"$rawbt_clear",
"$rawbt_cloudy",
"$binary_snow_cover",
"$salinity",
"$potential_temp",
"$humidity_mixing_ratio",
"$airframe_icing",
"$turbulence_index",
"$lidar_aerosol_extinction",
"$lidar_cloud_backscatter",
"$lidar_cloud_extinction ",
"$cloud_radar_reflectivity","$pstation",
"$pmsl",
"$pstandard",
"$vert_vv",
"$max_wind_shear1",
"$tot_zen_delay",
"$tot_zen_delay_err",
"$cloud_top_temp",
"$rawsca",
"$cloud_top_press",
"$mean_freq",
"$u_amb",
"$v_amb",
"$lwp",
"$tcwv",
"$theta",
"$cloud_frac_clear",
"$rawbt_hirs",
"$rawbt_amsu",
"$rawbt_hirs20",
"$sea_ice",
"$cloud_frac_covered",
"$level_mixing_ratio",
"$radial_velocity",
"$cloud_ice_water",
"$wind_gust",
"$mass_density",
"$atmosphere_number",
"$lightning",
"$level_cloud",
"$rawbt_amsr_89ghz",
"$max_wind_shear2",
"$lower_layer_p",
"$upper_layer_p",
"$cloud_cover",
"$depth",
"$ssh",
"$rawbt_mwts",
"$rawbt_mwhs"};

char *no[]={"3",
"4",
"1",
"57",
"29",
"9",
"58",
"2",
"59",
"39",
"40",
"11",
"30",
"60",
"61",
"62",
"63",
"64",
"65",
"66",
"67",
"68",
"69",
"70",
"71",
"72",
"73",
"74",
"75",
"76",
"77",
"78",
"79",
"80",
"81",
"82",
"83",
"84",
"85",
"86",
"87",
"88",
"89",
"90",
"91",
"92",
"110",
"111",
"112",
"119",
"120",
"121",
"122",
"5",
"6",
"41",
"42",
"19",
"123",
"124",
"125",
"7",
"126",
"127",
"8",
"56",
"206",
"156",
"215",
"160",
"130",
"12",
"192",
"128",
"162",
"187",
"174",
"163",
"181",
"182",
"183",
"184",
"185",
"175",
"176",
"177",
"178",
"179",
"180",
"201",
"211",
"195",
"186",
"188",
"189",
"190",
"191",
"202",
"203",
"222",
"220",
"221",
"193",
"194",
"223",
"224",
"225",
"226",
"227",
"228",
"236",
"237",
"238",
"239",
"107",
"108",               
"109",  
"218",            
"219",    
"229",      
"230",  
"231",     
"233",             
"235",    
"241",          
"242",              
"243",       
"244",                
"245",               
"225",
"247",   
"248",         
"249", 
"250",       
"253",            
"257", 
"258", 
"259",    
"260",    
"261",          
"262",
"263",  
"265",          
"266",        
"267",   
"268",    
"269",      
"270",      
"271",
"272",              
"273",                
"274",
"275"}  ; 
char *desc[]={"upper air u component",
"upper air v component",
"geopotential",
"thickness",
"upper air rel. humidity",
"precipitable water content",
"2m rel. humidity",
"upper air temperature (K)",
"upper air dew point (K)",
"2m temperature (K)",
"2m dew point (K)",
"surface temperature (K)",
"pressure tendency",
"past weather (w)",
"present weather (ww)",
"visibility",
"type of high clouds (ch)",
"type of middle clouds (cm)",
"type of low clouds (cl)",
"cloud base height (nh)",
"low cloud amount (n)",
"additional cloud group height (hh)",
"additional cloud group type (c)",
"additional cloud group amount (ns)",
"snow depth",
"state of ground (e)",
"ground temperature (tgtg)",
"special phenomena (spsp)#1",
"special phenomena (spsp)#2",
"ice code type (rs)",
"ice thickness (eses)",
"ice (is)",
"original time period of rain obs. (trtr)",
"6hr rain (liquid part)",
"max. temperature (jj)",
"ship speed (vs)",
"ship direction (ds)",
"wave height",
"wave period",
"wave direction",
"general cloud group",
"rel. humidity from low clouds",
"rel. humidity from middle clouds",
"rel. humidity from high clouds",
"total amount of clouds",
"6hr snowfall (solid part of rain)",
"surface pressure",
"wind direction",
"wind force",
"brightness temperature (K)",
"raw radiance",
"cloud amount from satellite",
"sigma 0",
"wind shear (du)",
"wind shear (dv)",
"10m u component (m/s)",
"10m v component (m/s)",
"layer rel. humidity",
"cloud liquid water",
"ambiguous v component",
"ambiguous u component",
"specific humidity (q)",
"ambiguous wind direction",
"ambiguous wind speed",
"vertical speed",
"virtual temperature",
"layer ozone",
"height",
"1d-var model level (pseudo)-variable",
"past weather 2 (used in synoptic maps)",
"characteristic of pressure tendency (used in synoptic maps)",
"sea water temperature (used in synoptic maps)",
"radar reflectivity",
"atmospheric path delay in satellite signal",
"radio occultation bending angle",
"horizontal line-of-sight wind component",
"aerosol optical depth at 0.55 microns",
"Limb Radiances",
"chem1: no2/nox",
"chem2: so2",
"chem3: so",
"chem4: hcho",
"chem5: go3",
"cloud optical depth",
"Ratio of fine mode to total aerosol optical depth at 0.55 microns",
"optical depth",
"Aerosol reflectance multi-channel",
"normalized soil moisture  (0-100%)",
"soil moisture",
"phase of aircraft flight",
"Height assignment method",
"radar doppler wind",
"ghg1: carbon dioxide",
"ghg2: methane",
"ghg3: nitrous oxide",
"brightness temperature real part",
"brightness temperature imaginary part",
"radar rain rate",
"log(radar rain rate mm/h + epsilon)",
"lidar backscattering",
"significant wave height (m)",
"surface wind speed (m/s)",
"brightness temperature for clear  (K)",
"brightness temperature for cloudy (K)",
"binary snow cover (0: no snow / 1: presence of snow)",
"ocean salinity (PSU)",
"potential temperature (Kelvin)",
"humidity mixing ratio (kg/kg)",
"airframe icing",
"turbulence index",
"lidar aerosol extinction",
"lidar cloud backscatter",
"lidar cloud extinction",
"cloud radar reflectivity","Station pressure (Pa)",
"Mean sea-level pressure (Pa)",
"Standard level pressure (Pa)",
"Vertical visibility (m)",
"Wind shear above and below 1st maximum wind in sonde profile (s-1)",
"Total zenith delay (GPS)",
"Total zenith delay error (GPS)",
"Cloud top temperature (K)",
"Scaled radiance",
"Cloud top pressure (Pa)",
"GPSRO mean frequency",
"Ambiguous u-wind component (m/s)",
"Ambiguous v-wind component (m/s)",
"Liquid water path",
"Total column water vapour",
"[alias to $potential_temp]",
"Cloud clear fraction",
"Raw brightness temperature specific to HIRS (K)",
"Raw brightness temperature specific to AMSU (K)",
"Raw brightness temperature specific to HIRS (K)",
"Sea ice fraction",
"Cloud covered fraction",
"[alias for $humidity_mixing_ratio]",
"Radial velocity from doppler radar",
"Cloud ice water",
"Maximum wind gust (m/s)",
"Mass density",
"SFERICS number of atmospheres",
"Lightning strike observation (ATDNET)",
"Cloud fraction (multi-level)",
"Raw brightness temperature specific to AMSR 89GHz channels (K)",
"Wind shear above and below 2nd maximum wind in sonde profile",
"Pressure at bottom of layer SBUV (Pa)",
"Pressure at top of later SBUV (Pa)",
"Total cloud cover",
"Depth (m)",
"Sea surface height (m)",
"Raw brightness temperature specific to MWTS (K)",
"Raw brightness temperature specific to MWHS (K)",} ; 

for ( long unsigned int i=0 ; i <= (sizeof (no ) /sizeof ( double)) -1  ; i++){
  printf (  "%s          %s          //%s \n" ,   vars[i], no[i], desc[i] ) ; 

}
return PyLong_FromLong(0) ;

}


static PyMethodDef module_methods[] = {
    {"odbTables",  (PyCFunction)(void(*)(void))   odbTables_method ,
     METH_VARARGS | METH_KEYWORDS,   "Show all existing ODB tables   "},
    {"odbVarno",  (PyCFunction)(void(*)(void))    odbVarno_method ,
     METH_VARARGS | METH_KEYWORDS,   "Print all ODB varno, parameters and description "},
};



// Modules definition
static struct PyModuleDef   odbmodule = {
    PyModuleDef_HEAD_INIT,
    "pyodb_info",
    "C/Python interface , show ODB varno, parameters and description",
    -1,
    module_methods ,
    .m_slots =NULL 
};



// Called first during python call
PyMODINIT_FUNC PyInit_pyodb_info(void) {
	PyObject* m  ; 
	PyObject* ModuleError ;  
        
	m= PyModule_Create(&odbmodule);
        if ( m == NULL) {
           ModuleError = PyErr_NewException("Failed to create the module : pyodb_info", NULL, NULL);
           Py_XINCREF(ModuleError) ;
        return NULL;	
      }
return m  ; 
}




