INTERFACE
SUBROUTINE BSSLZR_ODB(PBES,KNUM)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM), intent(in) :: KNUM
REAL(KIND=JPRB), intent(out)   :: PBES(KNUM)
END SUBROUTINE BSSLZR_ODB
END INTERFACE
