SUBROUTINE GAUAW_ODB(PA,PW,K,KRET)
USE PARKIND1  ,ONLY : JPIM,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM), intent(in)  :: K
REAL(KIND=JPRB), intent(out)    :: PA(K),PW(K)
INTEGER(KIND=JPIM), intent(out) :: KRET
END SUBROUTINE GAUAW_ODB
